apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-system
  namespace: flux-system
  labels:
    app: flux-system
    env: production
    category: core
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: flux-system
    creationPolicy: Owner
  data:
    - secretKey: githubAppID
      remoteRef:
        key: "flux-sync-app private key"
        property: github_app_id
    - secretKey: githubAppInstallationID
      remoteRef:
        key: "flux-sync-app private key"
        property: github_app_installation_id
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: "flux-sync-app private key"
        property: password
