apiVersion: v1
kind: ConfigMap
metadata:
  name: vmware-exporter-values
  namespace: monitoring
  labels:
    app: vmware-exporter
    env: production
    category: observability
data:
  values.yaml: |
    image:
      tag: v0.18.4

    vsphere:
      host: vcenter.vollminlab.com
      ignoressl: true
      collectors:
        hosts: true
        datastores: true
        vms: true

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    service:
      enabled: true
      type: ClusterIP
      port: 9272
      targetPort: 9272
