---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vmware-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    helm-values.yaml: AgDUsVBH6r8YCErqSp/TE7uW7oapFWEWPC5gKqGBK9W+2cLlFXwgFnMi5cspxIDvjUgiMtBIQU0th8igReWfVo9L5jsQ43ye26V5a4woKtYrANlJkHzo4KcPSLVQM9uKvvbn1PiTHhiMWwPSwhWMaXPiCaO9vusLHCIV5DTQ+H3hKoTyvvibWEMrADz2zqnSwcb/vIKXZQWrQmEHBu2cVKiBWpgSn9LY7tLFigOLdqVfnH4Gx5JfTZgAW+Q1LnXdoN5RUiADaUuIiVUTPYfjvsR16b+GQidK1VmI0GHROOaYHjrft9Lq1BHFnY9Gi5WUBfqGdBI/v4YE/bH3PL6kKY6Wna03jFDhprbfvBjGFslY5eO8tv382KuT914CV6QHFa1M/ttQjETSWbQw0z1cQg4SETwO91bSECEaWqxPX2/ttAjHUgxfocnZmBGYievZrsJkwWX+NqNZ3mGHNIK/BbM4ACCTMuJ9e80/aGQlAwyEX5AvmynvLF1qnu8Dx1NHQim8VlzDqWUYPq9zFzsH9o50UuZTnbxZdomUBFdo2iGu2WT0cPEhoChfSUgRm30UPb/Ln+mAwfbiGdt4hXcKWoattPhQAmqvzZFS2WGmyO0ClpGqVVmaIeIgBCh8GKuSeIUbrKn5nV9ZEJ4Ou0qinZN28vQwJP94+6fPKx5ljXXs3EryPZYYsl4ZeuoGxqEoow8cPJDpSs/aHo/TaXzHCf1FkpIIqMqhYNHWkIGR7DzvxPwXy2G35jV2UdwNPchIY+B+zSA5kaL7ipWj3/vqUw9773HXz7PGeMv/DLmQEt+cVR3klejQ
  template:
    metadata:
      name: vmware-exporter-credentials
      namespace: monitoring
