apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmware-exporter-credentials
  namespace: monitoring
  labels:
    app: vmware-exporter
    env: production
    category: observability
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: vmware-exporter-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        helm-values.yaml: |
          vsphere:
            user: "{{ .username }}"
            password: "{{ .password }}"
  dataFrom:
    - extract:
        key: "vCenter Metrics"
