apiVersion: v1
kind: Service
metadata:
  name: nut-exporter
  namespace: monitoring
  labels:
    app: nut-exporter
    env: production
    category: observability
spec:
  type: ClusterIP
  selector:
    app: nut-exporter
  ports:
    - name: metrics
      port: 9199
      targetPort: metrics
