apiVersion: v1
kind: ConfigMap
metadata:
  name: jellystat-values
  namespace: mediastack
  labels:
    app: jellystat
    env: production
    category: media
data:
  values.yaml: |
    image:
      tag: "1.1.10"
    postgresql:
      enabled: false
      auth:
        username: jellystat
        database: jellystat
    service:
      type: ClusterIP
      port: 3000
    podLabels:
      app: jellystat
      env: production
      category: media
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - velero
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
