apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-credentials
  namespace: mediastack
  labels:
    app: jellystat
    env: production
    category: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: jellystat-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        helm-values.yaml: |
          postgresql:
            auth:
              password: "{{ .postgresql_password }}"
          jwtSecret: "{{ .jwt_secret }}"
  dataFrom:
    - extract:
        key: "Jellystat Credentials"
