apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jellystat-app
resources:
  - configmap.yaml
  - helmrelease.yaml
  - ingress.yaml
  - jellystat-credentials-externalsecret.yaml
  - jellystat-postgresql-service.yaml
