apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: authentik
  labels:
    app: authentik
    env: production
    category: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: authentik-credentials
    creationPolicy: Owner
  data:
    - secretKey: values.yaml
      remoteRef:
        key: "Authentik Credentials"
        property: values_yaml
