apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-harbor-registry-restic
  namespace: harbor
  labels:
    app: harbor
    env: production
    category: storage
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: volsync-harbor-registry-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .b2_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .b2_key }}"
        RESTIC_PASSWORD: '{{ index . "harbor-registry" }}'
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/{{ .bucket }}/harbor/harbor-registry"
  dataFrom:
    - extract:
        key: "Volsync Restic Credentials"
