apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-minio-user
  namespace: minio
  labels:
    app: minio
    env: production
    category: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: cnpg-minio-user
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secretKey: "{{ .secret_access_key }}"
  dataFrom:
    - extract:
        key: "CNPG MinIO Credentials"
