apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-values
  namespace: minio
data:
  values.yaml: |
    mode: standalone
    replicas: 1

    deploymentUpdate:
      type: Recreate

    existingSecret: "minio-credentials"

    podLabels:
      app.kubernetes.io/name: minio
      env: production
      category: storage

    resources:
      requests:
        cpu: 150m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 100Gi

    service:
      type: ClusterIP
      port: "9000"

    consoleService:
      type: ClusterIP
      port: "9001"

    policies:
      - name: cnpg-policy
        statements:
          - effect: Allow
            resources:
              - "arn:aws:s3:::cnpg-backups"
              - "arn:aws:s3:::cnpg-backups/*"
            actions:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
      - name: tofu-state-policy
        statements:
          - effect: Allow
            resources:
              - "arn:aws:s3:::terraform-state"
              - "arn:aws:s3:::terraform-state/*"
            actions:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
              - "s3:ListBucket"
              - "s3:GetBucketLocation"

    users:
      - accessKey: cnpg-svc
        existingSecret: cnpg-minio-user
        existingSecretKey: secretKey
        policy: cnpg-policy
      - accessKey: tofu-svc
        existingSecret: tofu-minio-user
        existingSecretKey: secretKey
        policy: tofu-state-policy

    buckets:
      - name: velero
        policy: none
        purge: false
        versioning: false
        objectlocking: false
      - name: loki
        policy: none
        purge: false
        versioning: false
        objectlocking: false
      - name: cnpg-backups
        policy: none
        purge: false
        versioning: false
        objectlocking: false
      - name: terraform-state
        policy: none
        purge: false
        versioning: false
        objectlocking: false

    oidc:
      enabled: true
      configUrl: "https://authentik.vollminlab.com/application/o/minio/.well-known/openid-configuration"
      clientId: "GKq5oNsz9lgsa1kIOCM7uTa4qIBVe6SUsfVjeFCN" # gitleaks:allow
      existingClientSecretName: "minio-oidc-credentials"
      existingClientSecretKey: "MINIO_IDENTITY_OPENID_CLIENT_SECRET"
      claimName: "policy"
      scopes: "openid,profile,email"
      redirectUri: "https://minio.vollminlab.com/oauth_callback"
      displayName: "Authentik"

    extraEnvVars:
      - name: MINIO_IDENTITY_OPENID_PKCE_ENABLED
        value: "on"
      - name: MINIO_PROMETHEUS_AUTH_TYPE
        value: "public"

    makeBucketJob:
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
