apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio
  labels:
    app: minio
    env: production
    category: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        rootUser: "{{ .username }}"
        rootPassword: "{{ .password }}"
  dataFrom:
    - extract:
        key: "MinIO"
