apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
    env: production
    category: storage
spec:
  selector:
    matchLabels:
      app: minio
      monitoring: "true"
  endpoints:
    - port: http
      path: /minio/v2/metrics/cluster
      interval: 30s
      scheme: http
    - port: http
      path: /minio/v2/metrics/node
      interval: 30s
      scheme: http
    - port: http
      path: /minio/v2/metrics/bucket
      interval: 30s
      scheme: http
      honorTimestamps: false
