apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    app: authentik
    env: production
    category: security
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
