---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: readarr-tf-credentials
  namespace: tofu
spec:
  encryptedData:
    readarr_api_key: AgBSk98qjtKLboF6eiSYwGB4tR3nMK3NCE6qa7slOFMN2j2d7V8KGUew/62Urf/DBZj6nSI8lKVIsk5j50PQhLZ0wR09PTBsPtvSS7ud8HYa3TSmuEojciGTj4KTJ/l4S85xAfBAYxNnXwkYuMaJxQEEt5kA0Lwg53RUj/qHwkUQUM3BGuX02N/0yQbipserpHxi418CQG/ljMrSrX/Hzqzdx7fUB/HjSp2y5XVZwoeVEuemQJ5W9o+lShV5v9q+WMNiPeJy1CwL8PvDKZF7bmGpABMQkRKMC7I9/mZco9Jy+prNEFLnD+FW0t3WMc5ib9/gpzwnSrlJWcJtRg6Eq+HCJXhssh3s8PGYallnQZ6wbpeq2YEIdhj3LpNeugy7sByothrlAwxehWRlGdwZTswzql4S5DeTfm/R3yQbiF2IBTRPqDdVANzMBqX8TY6BLgINfaUTBMmhOUeZvy+8UpauQ6CdpYZqYD3hLQQNoM6nP1TBRG/FMtLNMHyt2GWVO0CzdeVinXGOV99kltuii1yoIF5JUHLzLOKCpBIb6hFbp2uBzGEZSli+jq86p53npVzw+3MtTaxQSjCdj4ODScbfbsgRA6tYV1ljQifU38MeYSi9COhDw71wEQUeu2wSDfBXmyDla+++icKvrBTHOfZAWrBh6v7EOKAakkyz9LWRFTu1V2cShNOgwCidwoixf5iNOK9aJjTgwf/6HTUvzju0t6uO+RlA1cWjGkTTk+1aSw==
    sabnzbd_api_key: AgAT1zWiJyplXarDBTrMmE/to4phVPzRyLIBTPSykNdalniQKlFnBy7rN7kF00bQgPuLeC8mtlHJqVEDNx5mQq/ibWWMwFC6P0Lw8zALLz5UsVLG0OGhMoAp/Q7ZbdNdZ4huTIDJ1Wdjg1R6HdAvGGHCnStkztMKdBkA8q6i41XTw1b5bJLBBE+Ry/E/RNrlfJOCegUgxt00xSt7qDbHi68aJ+bC7MfnRYdjkX+jkrK8JOFab/yXK6K1SDd+aeKZmbuevrSOMQNzoA567VVAUc+e33/JVEWB093vyhrd1Drlk2RhUFMP2T43dd3gaG4EWaCbTEaWi+H31XuyzAEg5q0bZd74F/uj7pmQXynzzTuF1QL1FN6erKyDPbpSry7n7dV/+C5pylIRH3dfKB64EdpyQEs3A+TpBTqyF+0KjSyl/Gb1nrODNb5C6PP0rTveM1BnoXEpSZh+8koAw2PRRPGqFJQvM3WDVzmOjGvuo4Q0MUG+GsauFX8P/kjZzbDhhRZnktIWLcuibQPPzpCeZPK+u+LtqEpGiYsxDEfJvZIDIuBA3iA4ayFk4A8nKbTQ2JmVxSe/lSbRufn+VF+uX7NqtZ4/5XxbjcHC5yRLew4WRAQH9OIAfd5zkBwDgCZVdzBPOMYkdbIQtrqgRujWdWvseC7NlqRmAKeYExHAjY5/B0KUmQqCREcmNquViHSZiQ2OZVqvHgIWyivoqOfVQsL6jqQG7muluX151AKPDtJ+2A==
  template:
    metadata:
      name: readarr-tf-credentials
      namespace: tofu
