apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-minio-credentials
  namespace: monitoring
  labels:
    app: loki
    env: production
    category: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: loki-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: "loki - Minio"
        property: accessKey
    - secretKey: secret-key
      remoteRef:
        key: "loki - Minio"
        property: credential
