apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-token
  namespace: renovate
  labels:
    app: renovate
    env: production
    category: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: renovate-token
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: "Renovate-Org-PAT"
        property: password
