apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: mediastack
  labels:
    app: qbittorrent
    env: production
    category: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: qbittorrent-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: qbittorrent-values
      valuesKey: values.yaml
