apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: qbittorrent-app
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc-qbittorrent-config.yaml
  - qbittorrent-pia-credentials-sealedsecret.yaml
