apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-pia-credentials
  namespace: mediastack
  labels:
    app: qbittorrent
    env: production
    category: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: qbittorrent-pia-credentials
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: "qBittorrent PIA Credentials"
        property: openvpn_user
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: "qBittorrent PIA Credentials"
        property: openvpn_password
