---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-pia-credentials
  namespace: mediastack
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgA2On4BmvxtY4ZVT7OLyt0IiwwMZlM/+lY/GxWK1W7mFEjxraU5lAOdaNmTlpjs9jRn5n3rqgeLKgh/EyQcbyYOBO0yCpriD2a+sso49z8s2R0leebOEFB3RdYuB5bNcoQeiYlu+RxadeAHHnTxEIBXMzSO16braMUt98Pmlt7J/kySQ3Cx/iRGvpz3w+s6dq4RxOnUDAhezgagLUp2BEzQFDVRN/sXUJmb2gu1O7jbh8Q2V8PtAPeeC7qgbtLqR7esJmDwlNxdi9g07D1n9GHRd84S99Cy8l/0gbMwR622tLSfFrxrr8vz7tqayqbKMT/hCMRY+rvD+5T4H27W0maEwX/7kATYfXqqT+hliQe1AVI3kMo17BabTzZXFxMMwKBm6V+E2vAwHIjGZ/OKTbYdsBM8G5xbJE+s2+UAM7F7Q4k6HyTQFFv0YHUyGH2nPc+0lJdXummsNm6GHuwpY/ETYxnbGh+JYO0MNhHhy0ZrPYbMxzJ6IzLDlBmVfx2NR2QfeB7I7n4ENI5TPc9cCxClikLjT/6kwxTIaVXHcEYToCXrdzqU2N7az0wmf2iZwAnqbc0pmHkwtRq+72NYwBCr3BkyAuDwM35nannOtXDvrf9zE6yvW9hffADrQ5re9FSg2iHq1PseT2HcOHjYn3H3YoFN8kJnkn6hVimYQk140FlQV9rxwDeE38+ozl8Jnk2CxEsq9gdB/spshvq0jb4H
    OPENVPN_USER: AgCHS4PEX/TKzHqeMz9e7w5qlgEWDmtahqID10ZPP6Dsx7yBOr1Wh6tzsaSNsVM9Hl2O6C1vTMpwCFbZQZkMJbIl0lkurRSfYr3dnxsKG5Yy4+SuJO6T7CIi3qffpuUyd2iboBcSZxIuaucUz8rq0BN7derFKe01Q1K2ghisYGhdzZzGA8E4TKp7+9qNlntijjwh8YuPLRUeaoEGGsNs/uQfNtMuavm2QubG/jGhdQXQki8r1XWW/25pSDkd31++l89WCTxnpWrnLRhpY50Ew6Wq56TYGNTiizA4ChtrFrWZlKwV63OgFXgb2X+WVouTrnBFNFXP6ixpN5/02NvuzRaixIlo25Fri/Fwv67I+Ke/upQ3Zsi1qNZt3TsIGbvQOjvMwUIUBPiaW5pbFvPPFbPcrQZHBDVyzW7v3sqAZBYZFKXLUZjiaq73BipzzMZgKmLqUp5ogSI+1mSFRYhD8EQX3F4s4q6ee9HKmpCg0FBKUf55rt+VXg6P1GhUZZeQQir1SiLKgv+kN6iOeCj+Y7xF1bfWn9JgOQxvq9QqwCM0Ba8mc4p9GxieNEVTx7tAGDWQiXlO41vn9RSBO6mWyx4O+mPRIFx4eYF1K71CjyPhh43PmBN+vCmyteRB7JbBwDw9h1Rr4+tm/bFum++n/A4aiP79aKBTzc+LoKXUE7DCVO9wKpqW9eAOX/XCQSeius/+oqk4iqFULA==
  template:
    metadata:
      name: qbittorrent-pia-credentials
      namespace: mediastack
