apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
  labels:
    app: velero
    env: production
    category: storage
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: velero-b2-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .keyID }}
          aws_secret_access_key={{ .applicationKey }}
  dataFrom:
    - extract:
        key: "Backblaze B2 - vollminlab-k8s-velero"
