apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-minio-credentials
  namespace: velero
  labels:
    app: velero
    env: production
    category: storage
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: velero-minio-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .access_key_id }}
          aws_secret_access_key={{ .secret_access_key }}
  dataFrom:
    - extract:
        key: "Velero MinIO Credentials"
