apiVersion: v1
kind: ConfigMap
metadata:
  name: vollmint-values
  namespace: vollmint
  labels:
    app: vollmint
    env: production
    category: apps
data:
  values.yaml: |
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
    sync:
      schedule: "10 6,18 * * *"
      suspend: false
