apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vollmint-simplefin
  namespace: vollmint
  labels:
    app: vollmint
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: vollmint-simplefin
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "SimpleFIN Access URL"
        property: token
