apiVersion: v1
kind: Namespace
metadata:
  name: mediastack
  labels:
    app: mediastack
    env: production
    category: media
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
