apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-credentials
  namespace: authentik
  labels:
    app: authentik
    env: production
    category: security
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: authentik-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "Authentik DB"
        property: username
    - secretKey: password
      remoteRef:
        key: "Authentik DB"
        property: password
