apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
  labels:
    app: authentik-db
    env: production
    category: security
spec:
  instances: 1
  inheritedMetadata:
    labels:
      app: authentik-db
      env: production
      category: security
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-credentials
      postInitSQL:
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO authentik
        - GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO authentik
        - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authentik
        - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO authentik
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/authentik-db"
      endpointURL: "http://minio.minio.svc.cluster.local:9000"
      s3Credentials:
        accessKeyId:
          name: cnpg-minio-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-minio-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        maxParallel: 2
    retentionPolicy: "7d"
