apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
  labels:
    app: goldilocks
    env: production
    category: observability
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
