apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-rebalancing-controller-values
  namespace: longhorn-system
  labels:
    app: longhorn-rebalancing-controller
    env: production
    category: storage
data:
  values.yaml: |
    podLabels:
      app: longhorn-rebalancing-controller
      env: production
      category: storage

    imagePullSecrets:
      - name: harbor-vollminlab-pull

    config:
      dryRun: true

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
