apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: trivy-system
  labels:
    app: trivy-operator
    env: production
    category: security
resources:
  - namespace.yaml
  - trivy-operator/app
