apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-foundry-data-restic
  namespace: foundry
  labels:
    app: foundry
    env: production
    category: gaming
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: volsync-foundry-data-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .b2_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .b2_key }}"
        RESTIC_PASSWORD: '{{ index . "foundry-data" }}'
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/{{ .bucket }}/foundry/foundry-data"
  dataFrom:
    - extract:
        key: "Volsync Restic Credentials"
