apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sabnzbd-exportarr
  namespace: mediastack
  labels:
    app: sabnzbd-exportarr
    env: production
    category: media
spec:
  endpoints:
    - path: /metrics
      port: metrics
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app: sabnzbd-exportarr
