apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sabnzbd-app
resources:
  - configmap.yaml
  - sabnzbd-exportarr-apikey-externalsecret.yaml
  - exportarr-deployment.yaml
  - exportarr-service.yaml
  - exportarr-servicemonitor.yaml
  - helmrelease.yaml
  - ingress.yaml
  - pvc-sabnzbd-config.yaml
