apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-exportarr-apikey
  namespace: mediastack
  labels:
    app: sabnzbd
    env: production
    category: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: sabnzbd-exportarr-apikey
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: "SABnzbd API Key"
        property: api_key
