apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1password
  namespace: flux-system
  labels:
    app: onepassword-connect
    env: production
    category: security
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/1password
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: 1password
  timeout: 5m
