apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterwide
  namespace: flux-system
  labels:
    app: clusterwide
    env: production
    category: core
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/clusterwide
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  dependsOn:
    - name: external-secrets
