apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
  labels:
    app: harbor
    env: production
    category: storage
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 15m
  dependsOn:
    - name: cnpg-system
    - name: longhorn-system
    - name: external-secrets
