apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-kustomizations
resources:
  - 1password-kustomization.yaml
  - cnpg-system-kustomization.yaml
  - cert-manager-kustomization.yaml
  - clusterwide-kustomization.yaml
  - ingress-nginx-kustomization.yaml
  - dmz-kustomization.yaml
  - metallb-system-kustomization.yaml
  - headlamp-kustomization.yaml
  - kyverno-kustomization.yaml
  - kyverno-webhooks-patch-kustomization.yaml
  - kyverno-policies-kustomization.yaml
  - policy-reporter-kustomization.yaml
  - policy-reporter-patch-kustomization.yaml
  - kube-system-kustomization.yaml
  - tailscale-kustomization.yaml
  - tailscale-connector-kustomization.yaml
  - arc-controller-kustomization.yaml
  - actions-runner-system-kustomization.yaml
  - actions-runner-system-runners-kustomization.yaml
  - external-dns-kustomization.yaml
  - external-secrets-kustomization.yaml
  - homepage-kustomization.yaml
  - local-path-storage-kustomization.yaml
  - longhorn-system-kustomization.yaml
  - mediastack-kustomization.yaml
  - monitoring-kustomization.yaml
  - portainer-kustomization.yaml
  - shlink-kustomization.yaml
  - minio-kustomization.yaml
  - renovate-kustomization.yaml
  - reloader-kustomization.yaml
  - velero-kustomization.yaml
  - vmware-exporter-kustomization.yaml
  - harbor-kustomization.yaml
  - authentik-kustomization.yaml
  - tofu-kustomization.yaml
  - goldilocks-kustomization.yaml
  - trivy-system-kustomization.yaml
  - volsync-kustomization.yaml
