apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
  labels:
    app: minio
    env: production
    category: storage
spec:
  interval: 10m
  path: ./clusters/vollminlab-cluster/minio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  dependsOn:
    - name: external-secrets
