apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  labels:
    app: local-path-provisioner
    env: production
    category: storage
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    goldilocks.fairwinds.com/enabled: "true"
