apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    app: harbor
    env: production
    category: storage
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
