---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-nginx-tunnel-credentials
  namespace: ingress-nginx
spec:
  encryptedData:
    tunnel-token: AgBcQE7vHqPJNMswn4QVxxWaEu+SZVQ2N1BiqMYX7Zgz/hbrvza5s934UJ3cGmPHrfOwsHhI5u+oBa8sTo0lkdGTYlW+0CYot8j+O75ZdtpmtKKGp/o3qqAfShyDIFmRL+Phl8H8ZPm9lRw8QO03/PJ92GZXrDZfH6ChuKknIzKcxVHcqZY3JNKphnG2bsG/cas3IdMkc5dAT/9xyiPg+prCzEUbOYBSajQKDVpWqZ5n0GXRMF/89UvdNbWvTazHVjHejvlHxpyGrT/Bewh5OHLgDznQuP94oWZLasFCdUmIav4yqOZhVBWeKRv1gZSPx19aILQaEMJ6IJqMv79Ho2FlARucz/L+6HSocORlpHPraVFtf3hxtHb9ZfchZwz9xGDVx8lXgGV4MMgeQkjmPD8fzJDtYU0OMX48rHDLeWokrIBaHp+sXYniGAljs+qakwV3N9Drx/rWXUnpOkNF9+IYZluGw8VKzB9kopmbejzUuEL177NNL1bjNm2KsuS7YwfjHqfnBiJazB3jXhbhOlFwMNsaGBdBd4eQF/A37n7FlbeZFSuUEhEE+9rjqbMty49nXytCaJZaQ+buMI7gDUHEyDJlPXp9wNRNr+zL0jNrIspQvddJylNas9bWzyIJ+PP5GZWClxMsEmBUXDDsZ4EttySp6L2h7vYx1QYqS0V9SbV4uBkpMWkZ0Trz+jrslIfO3O0xR/thAVshLhfZ1k0f6XksWmn9tmcUyv9sN2wfzMCpfAioJ9ajeaHLv1qZLpSx6yv/ixeMFZlWoHOdY686eBfwR9/wIyntMhGmmXmr1YvT5OzliWbQnr0Y7CGju6i0OsB6aF/sjBYpMBoTQSGE0SpOX2Ne0y03YuQWbzcqGhkzPfrKR0l26bDik5KXNiduQzkQAQKd8dvWZ6UrznLUhcD2GM804j1hD3WziGXdIUoO81mIJkFza0qFKsWlrkx+JimMzlomZcIQkN7cXIQ9rblAdmv1OzVa7lylV5gkBMkqbgaarCZRLdZu4uXk2Z0=
  template:
    metadata:
      name: cloudflared-nginx-tunnel-credentials
      namespace: ingress-nginx
