apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-nginx-tunnel-credentials
  namespace: ingress-nginx
  labels:
    app: cloudflared-nginx
    env: production
    category: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-nginx-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: "Cloudflare nginx Tunnel"
        property: token
