---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-jellyfin-tunnel-credentials
  namespace: mediastack
spec:
  encryptedData:
    tunnel-token: AgBCT5CprXl1WWLvvtqN9ukG6LBo5aM7LgJObdcgG+u6C22J5am/e+I+sTm0zn7oVuuSiWaTW/JY6ZfcGTQ8MI5IT1SH4LHqWo+wqgwrCV7RPDjPcOcCE5A1YowKN+H7aLWVjYquGtyZVuPk4iFBPhgnF0YXPStkrI5CdwkHMFGMp8a6KOXaCf0jGtIT+31BYLByawTU/sgEVLOEHhMoDs4NpZ0nGlEcFJOKznBQtJqRAXXvK7dIArJeceMkTtzfBz9dAmW4++AKd5awQiCafLIaWU0VDfxJy4Z7LriHlYH2VKxSLT0VuRo7Qh3tOX1p0D0nphjiR43fsC+FfSKzj3HysSto+kvR5/uASJvs4HA0IjhPBT7+8qiW9n3S1wJ4Bhwa3/ksRhsvRwmIJX2QmnR1cpt7MNvY4kBCVP8OptEvFxZhHWkoe1ed4p2ag6iKBYA596lA2OX/Y9g40XJ1jVSd+fBMzhYIsbDm1eVjihY20xYIHo3Avg+u3DB6LS4WR3jo80JdYXfSm0AtxRB8P5dgNvv40RSVkGTTCLA/9MNqNNFntT7U/MsWKDrfNEq3ydHwb7bXhlKbt6T7xpOog0obJsRWSP2n1fHXJIcivVQ7MNm8QwoZc2oghwYoQGoVx4Qd53Z0u3wz7+OXQczWFzH3gIgDQKTc/2oUqr6oV/4QpX10sgOBtqG6L6Tq6XhK4mKvQD8W1cYn4oAK8Bgkm3HSTzG1iTOaXvY2U5hS8vmsBFwRvGNv6HItcXsSvCHzp3/leKbmfaJzOpe2QLwXY/1blBawhh6hZVFQhHGthr3BWGXhLZZusSLHXOzQhbiskk2a3HlINfub5v80abvj+K72+8wkKuz67JZHO0HDt1+8Hmi6zXG7AwqYGN5yQLsGhvby/tvLAwAfe4qxWwDtvO0BgfInK+9vbxQoNmiknCJsdH5y4c6avL+diw+MlwoSeeT01Za78ibtTXJC9zwvjhh0hduDcJygCl9uszQ3y33NJjK1I10Px88iHphZmcXU11E=
  template:
    metadata:
      name: cloudflared-jellyfin-tunnel-credentials
      namespace: mediastack
