apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-minio-credentials
  namespace: shlink
  labels:
    app: shlink-db
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: cnpg-minio-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .access_key_id }}"
        ACCESS_SECRET_KEY: "{{ .secret_access_key }}"
  dataFrom:
    - extract:
        key: "CNPG MinIO Credentials"
