apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: shlink-db-backup
  namespace: shlink
  labels:
    app: shlink-db
    env: production
    category: apps
spec:
  schedule: "0 30 1 * * *"
  backupOwnerReference: self
  cluster:
    name: shlink-db
