apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rreading-glasses-hardcover
  namespace: mediastack
  labels:
    app: rreading-glasses
    env: production
    category: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: rreading-glasses-hardcover
    creationPolicy: Owner
    template:
      data:
        HARDCOVER_AUTH: "Bearer {{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: "vollminlab-readarr-metadata"
        property: credential
