apiVersion: v1
kind: Service
metadata:
  name: rreading-glasses
  namespace: mediastack
  labels:
    app: rreading-glasses
    env: production
    category: media
spec:
  type: ClusterIP
  selector:
    app: rreading-glasses
  ports:
    - name: http
      port: 80
      targetPort: 8788
