apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-pihole
  namespace: external-dns
  labels:
    app: external-dns
    env: production
    category: networking
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: external-dns-pihole
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
      remoteRef:
        key: "Pihole External DNS"
        property: password
