apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app: external-dns
    env: production
    category: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: 1.22.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
      valuesKey: values.yaml
