apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-vollminlab-pull
  namespace: monitoring
  labels:
    app: monitoring
    env: production
    category: observability
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: harbor-vollminlab-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"harbor.vollminlab.com":{"auth":"{{ printf "%s:%s" .username .password | b64enc }}","username":"{{ .username }}","password":"{{ .password }}"}}}'
  dataFrom:
    - extract:
        key: "Harbor Cluster Pull Robot Account"
