apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: monitoring
    env: production
    category: observability
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
