apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-rcon-secret
  namespace: dmz
  labels:
    app: minecraft
    env: production
    category: gaming
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: minecraft-rcon-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "Minecraft RCON"
        property: password
