apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: minecraft
  namespace: dmz
  labels:
    app: minecraft
    env: production
    category: gaming
spec:
  podSelector:
    matchLabels:
      app: minecraft
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.160.2/32  # HAProxy node 1
        - ipBlock:
            cidr: 192.168.160.3/32  # HAProxy node 2
      ports:
        - protocol: TCP
          port: 25565
        - protocol: TCP
          port: 8100  # Web map interface
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    - to:
        - ipBlock:
            cidr: 10.96.0.10/32  # kube-dns ClusterIP
      ports:
        - protocol: UDP
          port: 53
