apiVersion: v1
kind: ConfigMap
metadata:
  name: readarr-values
  namespace: mediastack
  labels:
    app: readarr
    env: production
    category: media
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-readarr-config
        mountPath: /config
      downloads:
        enabled: true
        existingClaim: pvc-completed-downloads
        mountPath: /downloads
      audiobooks:
        enabled: true
        existingClaim: pvc-audiobooks
        mountPath: /audiobooks
      books:
        enabled: true
        existingClaim: pvc-books
        mountPath: /books
    terminationGracePeriodSeconds: 60
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 10"]
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - velero
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podLabels:
      app: readarr
      env: production
      category: media
    podAnnotations:
      backup.velero.io/backup-volumes-excludes: "tmp,varlogs,varrun,devshm"
    image:
      repository: ghcr.io/pennydreadful/bookshelf
      tag: hardcover-v0.4.20.129@sha256:388eecc94362580eae31ee0a454be6af516f8a311f8432a521c202fb475f4359
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LSIO_NON_ROOT_USER: "true"
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
