apiVersion: v1
kind: ConfigMap
metadata:
  name: readarr-values
  namespace: mediastack
  labels:
    app: readarr
    env: production
    category: media
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-readarr-config
        mountPath: /config
      downloads:
        enabled: true
        existingClaim: pvc-completed-downloads
        mountPath: /downloads
      audiobooks:
        enabled: true
        existingClaim: pvc-audiobooks
        mountPath: /audiobooks
      books:
        enabled: true
        existingClaim: pvc-books
        mountPath: /books
    terminationGracePeriodSeconds: 60
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 10"]
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    podLabels:
      app: readarr
      env: production
      category: media
    image:
      repository: ghcr.io/pennydreadful/bookshelf
      tag: hardcover-v0.4.20.129@sha256:388eecc94362580eae31ee0a454be6af516f8a311f8432a521c202fb475f4359
    env:
      PUID: "568"
      PGID: "568"
      LSIO_NON_ROOT_USER: "true"
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - k8sworker03
