apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    app: tailscale-operator
    env: production
    category: networking
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
