apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-oauth-client-secrets
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: authentik-oauth-client-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "Authentik OAuth Client Secrets ESO"
