apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr-audio-apikey
  namespace: mediastack
  labels:
    app: readarr-audio
    env: production
    category: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: readarr-audio-apikey
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: "Readarr Audio API Key"
        property: credential
