apiVersion: v1
kind: ConfigMap
metadata:
  name: seerr-values
  namespace: mediastack
  labels:
    app: seerr
    env: production
    category: media
data:
  values.yaml: |
    podLabels:
      app: seerr
      env: production
      category: media

    config:
      persistence:
        existingClaim: pvc-seerr-config
        storageClass: longhorn

    ingress:
      enabled: false

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - velero
              topologyKey: kubernetes.io/hostname
    livenessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 10
      failureThreshold: 3
      periodSeconds: 15

    readinessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 10
      failureThreshold: 3
      periodSeconds: 15

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
