---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-tf-credentials
  namespace: tofu
spec:
  encryptedData:
    tailscale_oauth_client_id: AgAJNHGX5BFEAl+TP3lBgdOETsn6VDU/jhzX1kjJ4p9SQdCfqW6t+3biOCKu5otBrd9kL5/D2patm2OwoxpL5UxgHUzlv/jDlNV89aXxihqjlaEQCvpwRqIIaaoYdbxqdroCtW3F7N9uXiwcjcgdM056fAsFwOs+laRVFPIBnFIiFmJEfjEHyav5l5l2BLtetJXJcURVbUD2Wr6qDgM3iw0rGAe/EfEo6iwOpRkwa1EvPbpi89HF7LpTChqnN7UJTvZGdM0fr997qi6ZtWp78nMvcMS1GamUPlhOHTpTEh621o3h8++InXN8HV1OvjyugLaQsaZ5ANbts/95WqW40vdANsHKlyA3p4ohngEkAKrzlLvOgQeqkgTyXH81uoRa9eKsUnRqGYeoQ9+/Pf+1SqXiUWCAZwXGLgvZYaZqCajyZIDZG8vocoUK99e3WUQlKWDkGHwcE6YX1o3kRq7hpx3oEQwe/oXtPllsisITNj2rIZLB30XPynOFnsrk7FEG1f1RK98Woe/OKoeBCgVdifDsCYfuJ1xzsQjwt+NqBBHwa1hpwgLaYXRSxTN17qpUY8rkNLK3hQIqck+aMEEA3+7v+81zCfxSjYhqTxvnBgoKxbm3I84URo6f2cJfuCOSUoe/8B3N3OuvldzS0Od45vM6OlvdVcjFZEVSBfufYEmMrnWpJi/+lf5xJkPUePd+8XWbb6we43yuGVIYBi+fqs3u0g==
    tailscale_oauth_client_secret: AgB5XKYCQZ/yGx9dPOaEKXILohAxbheN47plKj5QL/kCFIFoUYHZ0sNQyN6cqO5rCuVTyuJAdtrv4l6ngjNLlmMeVNNMLGs0yvqqFbqKS3adByQYKnBLmxATHC5oJlIlX9xTzhjg+P6iheDrLUf/+yoz0ptOLZA9H6mYKJ3PaGlTz5uW1wwoMtItFz3zo2eK5ZeegKbLNmRALAt4Gr4nFtGYWmnmNJlpa1cj1KoNoFj1+47X4q5autSgkYCLsFlxuG3ujGQWQOgQMONM1nJd1+lO3SuGE+y8H/6J7LwPCD4QEO+jFJiPGIM2qj7Nailhby39HAwK7E0BbzlF4EyzD5h6g2DOBMwpKX1wYtITnnuCa0KZBb6U291yXv+tA8j8gfFDNYw4T1zxDTIYYRKOngfsNWdfunKgfcZKrWl6DsP9j/WJRKAmlx5lJfZNlqk9W/eGvm6VYkaHbAGQ6H5QEyfRbme2C689y4PZV8u5Q/HnfOJfeZqjRjYlTR16Z8CHqWyRXNrqo0aEElNwMG01TqmKLL6wiPrSbGLYoPKGza4mq51xEfR1xFI3mAKYuK9JcINRP5E8pmP1lB8MAYwL+woGnWxwNBtgpFHrO74NR3R8yf8rYpcowoCEl9nVeNvaXGKEo5Qv/H2q8ez/s9uRx+H5rUltq/rxDjrEyVldOKiTEifqhVbDsIF+cjN2S6L2sMB0l8tSUZXgxTXx0Ar7OERUyUWR1EOAHyCERR4j7uEWrBEObht+8Y2xe2bu5oXDL1K6kYYtDE91a74vtYzvNVDo
  template:
    metadata:
      name: tailscale-tf-credentials
      namespace: tofu
      labels:
        app: tofu-controller
        env: production
        category: core
