apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-tf-credentials
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: sonarr-tf-credentials
    creationPolicy: Owner
  data:
    - secretKey: sabnzbd_api_key
      remoteRef:
        key: "SABnzbd API Key"
        property: api_key
    - secretKey: sonarr_api_key
      remoteRef:
        key: "Sonarr API Key"
        property: credential
