apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homepage-app
  namespace: flux-system
resources:
  - configmap.yaml
  - helmrelease.yaml
  - homepage-custom-css-configmap.yaml
  - homepage-env-vars-externalsecret.yaml
  - ingress.yaml
  - rbac.yaml
  - pihole-watchdog-cronjob.yaml
