apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: filebrowser-config-restic
  namespace: mediastack
spec:
  sourcePVC: pvc-filebrowser-config
  trigger:
    schedule: "30 0 * * *"
  restic:
    pruneIntervalDays: 7
    repository: volsync-filebrowser-config-restic
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    copyMethod: Clone
    cacheCapacity: 1Gi
    cacheStorageClassName: longhorn
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
