apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-filebrowser-config-restic
  namespace: mediastack
  labels:
    app: mediastack
    env: production
    category: media
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: volsync-filebrowser-config-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .b2_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .b2_key }}"
        RESTIC_PASSWORD: '{{ index . "filebrowser-config" }}'
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/{{ .bucket }}/mediastack/filebrowser-config"
  dataFrom:
    - extract:
        key: "Volsync Restic Credentials"
