apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubeadm-cert-pushover
  namespace: kube-system
  labels:
    app: kubeadm-cert-monitor
    env: production
    category: core
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: kubeadm-cert-pushover
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "Kubeadm Cert Pushover"
        property: token
    - secretKey: user-key
      remoteRef:
        key: "Kubeadm Cert Pushover"
        property: user-key
