apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-values
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
    env: production
    category: networking
data:
  values.yaml: |
    controller:
      config:
        allow-snippet-annotations: "true"
        annotations-risk-level: Critical
        use-forwarded-headers: "true"
      extraArgs:
        default-ssl-certificate: cert-manager/wildcard-tls
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
