apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-values
  namespace: metallb-system
  labels:
    app: metallb
    env: production
    category: networking
data:
  values.yaml: |
    crds:
      enabled: true
    controller:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    frr-k8s:
      prometheus:
        serviceMonitor:
          enabled: false
      frrk8s:
        frr:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        frrMetrics:
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
        frrStatus:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
        reloader:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
        livenessProbe:
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          timeoutSeconds: 5
    speaker:
      enabled: true
      podAnnotations:
        backup.velero.io/backup-volumes-excludes: "frr-sockets,frr-conf,reloader,metrics,frr-tmp,frr-lib,frr-log"
      tolerations:
        - key: dmz
          operator: Exists
          effect: NoSchedule
        - key: dmz
          operator: Exists
          effect: NoExecute
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
