apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-authentik-tunnel-credentials
  namespace: authentik
  labels:
    app: cloudflared-authentik
    env: production
    category: security
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-authentik-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: "Cloudflare Authentik Tunnel"
        property: token
