---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-authentik-tunnel-credentials
  namespace: authentik
spec:
  encryptedData:
    tunnel-token: AgCfjfjCVK26c0kxW1wU95YdInhRNC4D80vxhxV7Qv0G0EllSnhXxjUMC1reFDHIh/Xaa0iePF+MMLqRXpDFP/0puqY28wn5Z0zfZOljhDTQrpKYzRY35PJBfuoH5HiDcGxwFlvUMVAy6gHC1qp+jyLDvOWYXq6ikzROC3X3g4D8teQ+jsG64RsTIrSn87vrDRBq1VavGB1JhR16BommK4disfNnx094sqQGna56mk7LSUGxC8T0Md40Htf0IECtPhL6DsT/39K2pjlZ1KHnS3sDKKoKizZoL8cqoqbEJ3VCgK7WXi1qEZ7fO0fgmDmy3wSFNFoKo2FpxPoHdZYqzAQy0ghbaX4Hbc1JQRJ9vla940FXe3Qa/46u0D5+8m6EIhht9cKwinFD48b9kimqZZ31qd0WWehFnjKPN31s7FsjryOaYpGdLG7KTJUpHnvH5sNoEbsvYzhWEa4U1y3wzl2ziaddN1kOcB5FY9jeXPwlhBQaNqfwWb6S9WHcXBJUgRV8+qFu4fNtL83YMgwDOEDl0rOh2jDJh8wgM593ocAufJpNNJEHBpiOjO3XD9V3/cIEqJyvLSBNaPF6a73I/D+9gSljRAmg6uOTBHa9ErAPKOMPa8690wGhvDcqgPF3X8syPqImyxn2/SjhoLAm2gNfKc0X9Ac+z7SVWYkG0mG3uyvl+LLivUs0BAGuqNpu9WAQyUSYgge93z49zvJtixMG6p1LdcvJlSyBcpE4iVmPQrVm+O0C4FhnCKov0jW+mVNpp4zjiHpIePnxdNDIx2zNgI3pr0hlKYKeFB5WG8RNcMuWXqTg+EZGFgDQCFSR8gcNtRTUuJ4rDzWKpMhxXGrUKj/68nrSFBEmCnuMpS0ukIQO8sO2bwin7VrUuNgX/977Js9HURbcc0yf/HZVWV54S4kzYtbeUlhia4frchtG9BSasjtGt0DSR/EP/KbyJLQ5WYdTBZ/z92oMnYGtUIDw7KLuAxkVpPrp8kBCxJFJ4pBs6HQSPtJvLP2NEcW49rM=
  template:
    metadata:
      name: cloudflared-authentik-tunnel-credentials
      namespace: authentik
