apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app: external-secrets
    env: production
    category: security
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
