apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foundry-credentials
  namespace: foundry
  labels:
    app: foundry
    env: production
    category: gaming
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: foundry-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "Foundry VTT"
        property: username
    - secretKey: password
      remoteRef:
        key: "Foundry VTT"
        property: password
    - secretKey: admin-key
      remoteRef:
        key: "Foundry VTT"
        property: admin_key
    - secretKey: license-key
      remoteRef:
        key: "Foundry VTT"
        property: license_key
