apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tf-credentials
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-tf-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_account_id
      remoteRef:
        key: "Cloudflare Terraform"
        property: cloudflare_account_id
    - secretKey: cloudflare_api_token
      remoteRef:
        key: "Cloudflare Terraform"
        property: credential
    - secretKey: cloudflare_zone_id
      remoteRef:
        key: "Cloudflare Terraform"
        property: cloudflare_zone_id
