apiVersion: v1
kind: Namespace
metadata:
  name: 1password
  labels:
    app: onepassword-connect
    env: production
    category: security
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
