apiVersion: v1
kind: ConfigMap
metadata:
  name: goldilocks-values
  namespace: goldilocks
  labels:
    app: goldilocks
    env: production
    category: observability
data:
  values.yaml: |
    vpa:
      enabled: true
      recommender:
        enabled: true
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
      updater:
        enabled: false
      admissionController:
        enabled: false

    controller:
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 256Mi

    dashboard:
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
      ingress:
        enabled: false
