apiVersion: v1
kind: ConfigMap
metadata:
  name: reloader-values
  namespace: reloader
  labels:
    app: reloader
    env: production
    category: core
data:
  values.yaml: |
    reloader:
      watchGlobally: true
      deployment:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
