apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-tf-credentials
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: b2-tf-credentials
    creationPolicy: Owner
  data:
    - secretKey: b2_master_application_key_id
      remoteRef:
        key: "Backblaze B2 Master Key"
        property: keyID
    - secretKey: b2_master_application_key
      remoteRef:
        key: "Backblaze B2 Master Key"
        property: credential
