apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-minio-credentials
  namespace: mediastack
  labels:
    app: jellystat-db
    env: production
    category: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: cnpg-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: "CNPG MinIO Credentials"
        property: access_key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: "CNPG MinIO Credentials"
        property: secret_access_key
