apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-db-credentials
  namespace: mediastack
  labels:
    app: jellystat-db
    env: production
    category: media
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: jellystat-db-credentials
    creationPolicy: Merge
  data:
    - secretKey: username
      remoteRef:
        key: "Jellystat DB Password"
        property: username
    - secretKey: password
      remoteRef:
        key: "Jellystat DB Password"
        property: password
