apiVersion: v1
kind: Namespace
metadata:
  name: fantasy
  labels:
    app: auction-board
    env: production
    category: apps
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
