apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc-credentials
  namespace: flux-system
  labels:
    app: headlamp
    env: production
    category: core
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: headlamp-oidc-credentials
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: "Headlamp OIDC Credentials"
        property: client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "Authentik OAuth Client Secrets ESO"
        property: headlamp_client_secret
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: "Headlamp OIDC Credentials"
        property: issuer_url
    - secretKey: OIDC_SCOPES
      remoteRef:
        key: "Headlamp OIDC Credentials"
        property: scopes
