apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: headlamp-app
  namespace: flux-system
resources:
  - clusterrolebinding.yaml
  - configmap.yaml
  - helmrelease.yaml
  - headlamp-oidc-credentials-externalsecret.yaml
  - ingress.yaml
  - networkpolicy.yaml
