apiVersion: v1
kind: ConfigMap
metadata:
  name: bazarr-values
  namespace: mediastack
  labels:
    app: bazarr
    env: production
    category: media
data:
  values.yaml: |
    securityContext:
      runAsUser: 568
      runAsGroup: 568
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    env:
      PUID: "568"
      PGID: "568"
      UMASK: "002"
      BAZARR__AUTH__USERNAME: ""
      BAZARR__AUTH__PASSWORD: ""
    persistence:
      config:
        enabled: true
        existingClaim: pvc-bazarr-config
        mountPath: /config
      downloads:
        enabled: true
        existingClaim: pvc-completed-downloads
        mountPath: /downloads
      tv:
        enabled: true
        existingClaim: pvc-tv
        mountPath: /tv
      movies:
        enabled: true
        existingClaim: pvc-movies
        mountPath: /movies
    podLabels:
      app: bazarr
      env: production
      category: media
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - velero
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
