apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: mediastack
  labels:
    app: mediastack
    env: production
    category: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: smb-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "SMB Credentials"
        property: username
    - secretKey: password
      remoteRef:
        key: "SMB Credentials"
        property: password
