apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-values
  namespace: mediastack
  labels:
    app: prowlarr
    env: production
    category: media
data:
  values.yaml: |
    persistence:
      config:
        enabled: true
        existingClaim: pvc-prowlarr-config
        mountPath: /config
    podLabels:
      app: prowlarr
      env: production
      category: media
    podAnnotations:
      backup.velero.io/backup-volumes-excludes: "tmp,varlogs,varrun,devshm"
    env:
      PROWLARR__AUTH__METHOD: "External"
    terminationGracePeriodSeconds: 60
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 10"]
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
