apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: minio-config
  labels:
    app: tofu-controller
    env: production
    category: core
resources:
  - minio-tf-credentials-externalsecret.yaml
  - terraform-cr.yaml
