apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-tf-credentials
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: minio-tf-credentials
    creationPolicy: Owner
  data:
    - secretKey: minio_access_key
      remoteRef:
        key: "MinIO"
        property: username
    - secretKey: minio_secret_key
      remoteRef:
        key: "MinIO"
        property: password
