apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: trivy-operator-deployment
  namespace: flux-system
  labels:
    app: trivy-operator
    env: production
    category: security
resources:
  - helmrelease.yaml
  - configmap.yaml
