apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-proxy-token
  namespace: authentik
  labels:
    app: authentik-proxy
    env: production
    category: security
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: authentik-proxy-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "Authentik Proxy Token"
        property: token
