apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password-connect-repo
  namespace: flux-system
  labels:
    app: onepassword-connect
    env: production
    category: security
spec:
  interval: 1h
  url: https://1password.github.io/connect-helm-charts/
