apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets-repo
  namespace: flux-system
  labels:
    app: external-secrets
    env: production
    category: security
spec:
  interval: 1h
  url: https://charts.external-secrets.io
