apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: foundry-repo
  namespace: flux-system
  labels:
    app: foundry
    env: production
    category: gaming
spec:
  url: https://charts.derwitt.dev
  interval: 5m
