apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-vollminlab-pull
  namespace: flux-system
  labels:
    app: flux-system
    env: production
    category: core
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: harbor-vollminlab-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: "Harbor Cluster Pull Robot Account"
        property: dockerconfigjson
