---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-vollminlab-pull
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgDKEkAAr99WofglQ8JAF1HBh4VEIwUOgbt8loQMWFxwakVtkyeSmz2XhvqHs+8e/9nSZWep6yAU7mP6uTT/FM55ABOjbRFHrR3dqDyfv/w+bC8J9MbRoxXh8M34ZAQFr0nHMM+o/teaSOQvsNkdHVYrJIsvBuckP06+dGaS8e4BSUF7j6KzjJc109BsHhTSzb3KE/g1IxvPLlYNer2FcssjbN6cjAU5jh5QjMy9pXkVk+isx9adZcCSDYO0PqXZyUP+NEA1jz3/wQ1lMNl82ut7199+cUkQ+DzDdxLPB0XwqduzrcHv6IXJZeTYkBR6b9yvl3mAkwx8ZzKwc7vAxbm48wAuYK/OuqFeTWyo8N4O7hl9AM2s7YSwlRq0EFNhc6Xi6YOtUksKow1duhyXSyXxp+UgOyFDa6kOzl3fCsWHyrXQjD3vzHXgyk1W2bxixNdYdqe29o/5BTIGI6sty9lgKQBN5CeVbGhdbdf7IysyMiKEXB8xTnO6OjQI8TuBQdP9xgpnlCDW4GXGiXt1a6tJQ1v4lIgpfBwxtGs1s5p3DXS4ojY0d0OR9Nlx9OVCg2MarvfUW+lvcqxHxR0pqUGFllr4w1LXMN91xfdWqor2sHAu18naAJPc9MwhEhwpvklzRSA61JqWu8ozv2FpWKchskT+1j6Lddfg0Y5l3cPESlRLz5VCWi3gzjXRFiD/+yNNCdDFeWpk6hYCz3r2fqm67CiGCixpVRhfrgJYwkrilWfkaE+LtqYPxqLuYDI6JPuaH6ZsLNYHmWwOrxe6A97YWqOA6kar1lDTz4ygTUVCCGjuOBfZ20B0slGoyHELPFgng6rjYhPoqCoCQlDto0BkTfC1WQSDe/UgKrJ56ZKBVthk6lAJ5g0swm8YkkTyHxQeUYiSd+4Y+kAR7DtzrfzlhWSGliJGPmyPaPW/H93G8DDQy2REnIjnwxRa6Y+PFwznx53wAE2MK37QXpS8tNrHW5xf8No/C40pSBZHEjL+JdFG8LiVjmcMMyW/mYYlZhM5rY1cXP+W
  template:
    metadata:
      name: harbor-vollminlab-pull
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
