apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-repositories
  labels:
    app: flux-repositories
    env: production
    category: system
resources:
  - 1password-connect-helmrepository.yaml
  - arc-controller-ocirepository.yaml
  - arc-runners-ocirepository.yaml
  - audiobookshelf-ocirepository.yaml
  - authentik-helmrepository.yaml
  - bazarr-helmrepository.yaml
  - cert-manager-helmrepository.yaml
  - cnpg-helmrepository.yaml
  - descheduler-helmrepository.yaml
  - external-dns-helmrepository.yaml
  - external-secrets-helmrepository.yaml
  - goldilocks-helmrepository.yaml
  - grafana-helmrepository.yaml
  - harbor-helmrepository.yaml
  - headlamp-helmrepository.yaml
  - homepage-helmrepository.yaml
  - ingress-nginx-helmrepository.yaml
  - jellyfin-helmrepository.yaml
  - jellystat-helmrepository.yaml
  - kyverno-helmrepository.yaml
  - kyverno-policyreporter-helmrepository.yaml
  - local-path-provisioner-gitrepository.yaml
  - longhorn-helmrepository.yaml
  - metallb-helmrepository.yaml
  - metrics-server-helmrepository.yaml
  - minecraft-helmrepository.yaml
  - minio-helmrepository.yaml
  - portainer-helmrepository.yaml
  - prometheus-community-helmrepository.yaml
  - prowlarr-ocirepository.yaml
  - radarr-ocirepository.yaml
  - readarr-ocirepository.yaml
  - reloader-helmrepository.yaml
  - renovate-ocirepository.yaml
  - sabnzbd-ocirepository.yaml
  - seerr-ocirepository.yaml
  - sealed-secrets-helmrepository.yaml
  - shlink-helmrepository.yaml
  - smb-csi-driver-helmrepository.yaml
  - sonarr-ocirepository.yaml
  - tailscale-operator-helmrepository.yaml
  - tofu-controller-helmrepository.yaml
  - trivy-operator-helmrepository.yaml
  - velero-helmrepository.yaml
  - vmware-exporter-helmrepository.yaml
  - volsync-helmrepository.yaml
  - harbor-vollminlab-pull-sealedsecret.yaml
  - vollminlab-ocirepository.yaml
