apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: longhorn-rebalancing-controller-repo
  namespace: flux-system
  labels:
    app: longhorn-rebalancing-controller
    env: production
    category: storage
spec:
  interval: 1h
  url: oci://harbor.vollminlab.com/vollminlab/charts/longhorn-rebalancing-controller
  ref:
    tag: "0.1.0"
  secretRef:
    name: harbor-vollminlab-pull
