apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prowlarr-repo
  namespace: flux-system
  labels:
    app: prowlarr
    env: production
    category: apps
spec:
  url: oci://oci.trueforge.org/truecharts/prowlarr
  interval: 5m
  ref:
    tag: 22.3.0
