apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: qbittorrent-repo
  namespace: flux-system
  labels:
    app: qbittorrent
    env: production
    category: media
spec:
  url: oci://oci.trueforge.org/truecharts/qbittorrent
  interval: 5m
  ref:
    tag: 25.4.0
