apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radarr-repo
  namespace: flux-system
  labels:
    app: radarr
    env: production
    category: apps
spec:
  url: oci://oci.trueforge.org/truecharts/radarr
  interval: 5m
  ref:
    tag: 23.26.0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy