apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sabnzbd-repo
  namespace: flux-system
  labels:
    app: sabnzbd
    env: production
    category: apps
spec:
  url: oci://oci.trueforge.org/truecharts/sabnzbd
  interval: 5m
  ref:
    tag: 21.9.6
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy