apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sonarr-repo
  namespace: flux-system
  labels:
    app: sonarr
    env: production
    category: apps
spec:
  url: oci://oci.trueforge.org/truecharts/sonarr
  interval: 5m
  ref:
    tag: 23.8.3
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy