apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics-repo
  namespace: flux-system
  labels:
    app: victoria-metrics
    env: production
    category: observability
spec:
  interval: 5m
  url: https://victoriametrics.github.io/helm-charts/
  timeout: 3m
