apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vollminlab-repo
  namespace: flux-system
  labels:
    app: vollminlab-repo
    env: production
    category: apps
spec:
  interval: 1h
  url: oci://harbor.vollminlab.com/vollminlab/charts/shlink-ingress-controller
  ref:
    tag: "0.3.5"
  secretRef:
    name: harbor-vollminlab-pull
