apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-tf-credentials
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: harbor-tf-credentials
    creationPolicy: Owner
  data:
    - secretKey: harbor_admin_password
      remoteRef:
        key: "Harbor Admin"
        property: password
    - secretKey: harbor_cluster_pull_secret
      remoteRef:
        key: "Harbor Cluster Pull Robot Account"
        property: password
    - secretKey: harbor_dockerhub_token
      remoteRef:
        key: "vollminlab-harbor-proxy-cache"
        property: credential
    - secretKey: harbor_dockerhub_user
      remoteRef:
        key: "Docker Hub"
        property: username
    - secretKey: harbor_gha_robot_secret
      remoteRef:
        key: "Harbor GHA Robot Account"
        property: password
    - secretKey: harbor_oidc_client_secret
      remoteRef:
        key: "Authentik OAuth Client Secrets ESO"
        property: harbor_client_secret
