apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-tf-credentials
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: prowlarr-tf-credentials
    creationPolicy: Owner
  data:
    - secretKey: nzbgeek_api_key
      remoteRef:
        key: "NZBGeek"
        property: api_key
    - secretKey: nzbplanet_api_key
      remoteRef:
        key: "NZBPlanet API Key"
        property: credential
    - secretKey: prowlarr_api_key
      remoteRef:
        key: "Prowlarr API Key"
        property: credential
    - secretKey: radarr_api_key
      remoteRef:
        key: "Radarr API Key"
        property: credential
    - secretKey: sonarr_api_key
      remoteRef:
        key: "Sonarr API Key"
        property: credential
