apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-tf-credentials
  namespace: tofu
  labels:
    app: tofu
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: grafana-tf-credentials
    creationPolicy: Owner
  data:
    - secretKey: grafana_admin_password
      remoteRef:
        key: "Grafana Admin Password"
        property: password
    - secretKey: grafana_client_secret
      remoteRef:
        key: "Authentik OAuth Client Secrets ESO"
        property: grafana_client_secret
    - secretKey: pushover_api_token
      remoteRef:
        key: "Pushover API Token"
        property: credential
    - secretKey: pushover_user_key
      remoteRef:
        key: "Pushover API Token"
        property: userKey
