---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-audiobookshelf-tunnel-credentials
  namespace: mediastack
spec:
  encryptedData:
    tunnel-token: AgAYAiSE0IihhpDkveft3KikRcGkQGeFj1CiqiR7nVLRZ5gS7epaUnpKLE3AR6CNGW/Ma1LwV+Qp7zKQDqPs4NoRjAp1MK/7ZfLj78fGUTGdAanIG5a6raBmxQmWrpWlkmy3HYewgnAJArm9Y3xo/t65pOpMBdHPgNsGrJvMsQHZhLwAfFpjXmbsreJOgjziJ3le1VTs6ASoxD6tWgAWOqQU6aogBKMliccnC1j5K+NBgci6SK+cct4Ld2L1B/WRTZeL12tQvWPf6uQ801EQA78NMw9dPbY1vrOipdiLi3sN9C+nARxh3MhvURT/zsJJhcbHv8S/eQACkyl1Nc45OAUS+1TyDm7WiHcb5SW0Mgqvm0jQLJwMvguWrZsUqTkCJ6sCn3Re0OT+hzt2ET9KVAQPy7GOpOQuAOEArP2xEghct8v7pCyAEPtEVR5sLO5BEIC6DvVpDmNhdtpVM9jyVdqZVNyg66rreBREnkCwZYO1h+3Px64Zzeqr/lPgBsVj56OOJqmz6w/XqFWEPvVInbjwko2JNiuTXIb0DNygv78/ZoiRfZLxhJ/6CyntG8OIhauxVJmqHJdJBfVndzLL1YcK7xZScewF/yAbXftJDodclY1G0iYwe9eYYZFSukdMg2DvrIpaZbIUvvkRbOWv5qKf5mSYaoPm+v8ZsC+9PzVV91YLPKXPuInGohfcEblmk4ky/yExv9517DEooSbKT9RNRa0GJeTT7gAO075pZvIYy4kdke9fF1RWzZtcDJgPiorC1nV5g1ZXCA4a4ZOYWG6p2Tn2br6PDrlV/wq9bM3sPwelXKsHiYvnE4uHf/uXCce5OV+AbR9R6PfXYbABbiXrs8vyb9Yg7Q6rNgODI2nuPzTIiH+kaejscoh47TOfRaLiaeV1GX8JJSzFoTi7iOssdB4uH7/q88B/5i79CdihV3QG1tJtJyZOb4uTNQbJrZzuFZwUwxtd5ph/AbOSZpmjlWVgc/FYhxyvJzGZ2fB8++PHkBeMFB3lv1ev/tP6y9Y=
  template:
    metadata:
      name: cloudflared-audiobookshelf-tunnel-credentials
      namespace: mediastack
