apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-audiobookshelf-tunnel-credentials
  namespace: mediastack
  labels:
    app: cloudflared-audiobookshelf
    env: production
    category: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-audiobookshelf-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: "Cloudflare Audiobookshelf Tunnel"
        property: token
