apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: clusterwide
resources:
  - kyverno-patch-clusterrole.yaml
  - kyverno-patch-clusterrolebinding.yaml
  - pv-audiobooks.yaml
  - pv-books.yaml
  - pv-completed-downloads.yaml
  - pv-audiobooks-incoming.yaml
  - pv-incomplete-downloads.yaml
  - pv-misc-incoming.yaml
  - pv-movies.yaml
  - pv-tv.yaml
  - storageclass-smb.yaml
  - storageclass-longhorn-dmz.yaml
  - disk-cleanup-rbac.yaml
  - disk-cleanup-cronjob.yaml
  - onepassword-cluster-store.yaml
