apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-cluster-store
  labels:
    app: onepassword-cluster-store
    env: production
    category: security
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password.svc.cluster.local:8080
      vaults:
        Homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect
            namespace: 1password
            key: token
