apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  labels:
    app: reloader
    env: production
    category: core
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
