apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    app: minio
    env: production
    category: storage
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
