apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shlink-credentials
  namespace: shlink
  labels:
    app: shlink
    env: production
    category: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: shlink-credentials
    creationPolicy: Owner
  data:
    - secretKey: database-password
      remoteRef:
        key: "Shlink DB Credentials"
        property: password
    - secretKey: initial-api-key
      remoteRef:
        key: "Shlink Initial Key"
        property: credential
    - secretKey: postgresql-password
      remoteRef:
        key: "shlink-credentials"
        property: postgresql-password
