apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-githubapp-secret
  namespace: actions-runner-system
  labels:
    app: arc-runners
    env: production
    category: ci
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: arc-githubapp-secret
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: "gha-arc-vollminlab-app private key"
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: "gha-arc-vollminlab-app private key"
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: "gha-arc-vollminlab-app private key"
        property: password
