apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
  labels:
    app: kyverno
    env: production
    category: security
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: kyverno-repo
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: kyverno-values
      valuesKey: values.yaml