apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover-config
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    env: production
    category: observability
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-pushover-config
    creationPolicy: Owner
  data:
    - secretKey: alertmanager.yaml
      remoteRef:
        key: "Alertmanager Config"
        property: config
