apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    env: production
    category: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: "Grafana Admin Password"
        property: username
    - secretKey: admin-password
      remoteRef:
        key: "Grafana Admin Password"
        property: password
