apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-deployment
  namespace: flux-system
  labels:
    app: kube-prometheus-stack
    env: production
    category: observability
resources:
  - helmrelease.yaml
  - configmap.yaml
  - ingress.yaml
  - alertmanager-pushover-config-externalsecret.yaml
  - grafana-admin-credentials-externalsecret.yaml
  - prometheusrule-custom.yaml
  - prometheusrule-eso.yaml
  - prometheusrule-gitops.yaml
  - nodes-dashboard-configmap.yaml
  - longhorn-dashboard-configmap.yaml
  - minio-dashboard-configmap.yaml
  - velero-dashboard-configmap.yaml
  - vmware-hosts-dashboard-configmap.yaml
  - vmware-datastores-dashboard-configmap.yaml
