# Ensure Kyverno CRDs exist before applying policies
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno-cluster-policies
resources:
  - dmz-enforce-node-placement.yaml
  - dmz-restrict-external-access.yaml
  - exceptions-calico.yaml
  - exceptions-ci-test-namespaces.yaml
  - exceptions-tailscale.yaml
  - exceptions-kyverno-hooks.yaml
  - exceptions-kubeadm-cert-renew.yaml
  - exceptions-longhorn-dynamic.yaml
  - flux-exception.yaml
  - inject-namespace-labels.yaml
  - inject-pod-labels.yaml
  - inject-resource-requirements.yaml
  - mutate-default-sa-automount.yaml
  - mutate-default-sa-pod-automount.yaml
  - require-labels.yaml
  - require-resources.yaml
  - restrict-default.yaml
  - restrict-image-registries.yaml
  - restrict-hostpath.yaml
  - restrict-latest-tag.yaml
  - restrict-loadbalancer.yaml
  - restrict-privileged.yaml
