apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app: ingress-nginx
    env: production
    category: networking
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    goldilocks.fairwinds.com/enabled: "true"
