apiVersion: v1
kind: Namespace
metadata:
  name: arc-controller
  labels:
    app: arc-controller
    env: production
    category: ci
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    goldilocks.fairwinds.com/enabled: "true"
