apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-credentials
  namespace: harbor
  labels:
    app: harbor
    env: production
    category: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: harbor-core-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REGISTRY_PASSWD: "{{ .password }}"
        REGISTRY_HTPASSWD: "{{ .REGISTRY_HTPASSWD }}"
  dataFrom:
    - extract:
        key: "Harbor Core"
