apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-vollminlab-pull
  namespace: shlink
  labels:
    app: shlink-ingress-controller
    env: production
    category: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-cluster-store
    kind: ClusterSecretStore
  target:
    name: harbor-vollminlab-pull
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"harbor.vollminlab.com":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  dataFrom:
    - extract:
        key: "Harbor Cluster Pull Robot Account"
