apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shlink-ingress-controller
  namespace: shlink
  labels:
    app: shlink-ingress-controller
    env: production
    category: apps
spec:
  interval: 10m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: vollminlab-repo
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: shlink-ingress-controller-values
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: shlink-ingress-controller
              spec:
                template:
                  spec:
                    imagePullSecrets:
                      - name: harbor-vollminlab-pull
            target:
              kind: Deployment
              name: shlink-ingress-controller
