apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-operator-values
  namespace: tailscale
  labels:
    app: tailscale-operator
    env: production
    category: networking
data:
  values.yaml: |
    operatorConfig:
      hostname: vollminlab-cluster-operator
      defaultTags:
        - tag:k8s
      image:
        repository: ghcr.io/tailscale/k8s-operator
        pullPolicy: IfNotPresent

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 256Mi
