---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBYX6Q4L/f/OS9Hrdp8EShVPtwJrSVXIrmfhcsOiZVMb8RDlH1hNVYhj5UvhZcp/8wTVIQcj0q2vSpnbbqubEuIhQ0oJs3DN0guyJcjME4C+L5JVrxBGiNH8rB/qy06+wI1xTN5jsFYNjCuGyXEQwwJK2tS7e6HlHWEiCB/NmgsDXqnQMzRABOiSEde+YGLQ5GuUYcvtByxBQ/GJwC1TjaYRS3juS3HUJ6A9A1gBEDMygcKPTNpTXfeO8uxRYp/dIiBwko+wpdrh6Uf0jRcEB7qAZlEEtbdTWW0GUwHhTF/4qp+kiH/gcAOHCf/PLfiyseZERlcJMMoZU2cdEOsf6SkiCAZd7GLLiCXgJrf58OnxoXV+GN2E/Rso5++NJCNaR8xEAx6ccaB/7ZesJCQFDBRdAhwOubQD4UKGsN1+V1f+faNPhZc4qNyH/7IgQ2fGiembF3yVDpunVK1XLJA+oKv36x9tycmgkxsbSZ8JbP8TlhHoXDMcky4nIPLq7whTZaMBhAM2R1v+p9h20iItvLJMUASJicnsPy1JobMuoYOlN+RtpThSi+sZL8c3XXNQYoIK2i3HGYZ5+3eUor7dflsN5qWP5GcBK16JRKimlXLQ15gNu+ceJo/1pqOEH/lidBCchRtFa02RS2Fp92sZMcXt5EiNLAEV5p+MyoZykoePIeu2SUwGm5wKo4y6BvsGBVH52bcOntI1TPXmblGrTg63w==
    client_secret: AgCf3kRTWCGjumYLIF5jTf6bSf+sEoJX9gCgR311WC7JzIjQCVMS4XPZC7DZuftFkPjGpR9x0o/coGQD9BB5kJP3bUOHMysVu8XVraj7rOp8HlmvkuOTY62jWrfD3gATbQR6FpUIJsq6dFMDqSsibBKlzfk3tT93z4YSiG89L5Dh0QSIsgyaCUsoGH75dDARhfWH5sBZfJN5NF5DlqIt3+0sVkZOKynT3UwFRfyygX70PbBqKRw2ZIzQlsSNj6fwYa/6NplzmVdzmgTXC/LLNL/a09oNTYu5wyLycS11HiassyRAIx5hERBwNPY9CVmYYGIA9UnCTapHLM5H7qf/FtNH5v0Xaosf8aqytTMrQ3Ox5hm1bNr9Y9dk98VHCqu7Dn7BECOlsQI0jXUhBcO7QWm9tQw11NmTU0PAfGMUtrShSP6vcDvKNUkmieAA4al/co6S+8VdU8NmUzz/R3vYaN2ctRTC0KyD2K/pMYK6Bc6ZeKXKBDtRTrJQsLo2oBwA2g4MNRP4tjUT+vRkgyWsoQYixldCl78Io6ykRekd+GYVoutGzXax2y3bQbcLJDgesI8+dS8XJrPwlg5xaY1kcBnTnUe8PgGkU/gehEIdn91Vcmdcp0r7w9AHbne7LsbbLY1NDFTddTnE/XY6+JTxatnpDrCCLVm3FZ8awphbWUefrzR72F94n+8333zO+lYSSw9Ar9IFotSttx3QTv53Z0O+2c7JPeFksxvfK/ywK2sj5hIzemLrPfB7oVlORwNozlVHaLopFaGjka7/22ZNAJnz
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
      labels:
        app: tailscale-operator
        env: production
        category: networking
